version: "3.8"

services:
  echo_redis:
    image: redis
    container_name: my-redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - echo-demo-stack

  echo_postgres:
    image: georgiyiakunenko/fooddelivery-postgres
    container_name: my-fooddelivery-postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - echo-demo-stack

  echo_goapp:
    image: fooddelivery-golang:2.0.1
    container_name: fooddelivery-golang-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - echo-demo-stack

networks:
  echo-demo-stack: